package ed.grupo4.GUI;

import java.awt.Color;
import javax.swing.JPanel;

public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        JPanel appinfo=new PanelRedondeado(20, Color.WHITE);
        appinfo.setBounds(480,100,300,350);
        appinfo.setOpaque(false);
        Inicio.add(appinfo);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new PanelFondo("/ed/grupo4/resources/images/patron.jpg");
        Opciones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        btnPasajeros = new javax.swing.JLabel();
        btngestioncabinas = new javax.swing.JLabel();
        btnabordarpasajeros = new javax.swing.JLabel();
        btnmostrarcolas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Inicio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setLayout(new java.awt.BorderLayout());

        Opciones.setBackground(new java.awt.Color(204, 204, 204));
        Opciones.setPreferredSize(new java.awt.Dimension(1280, 175));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/icono_casa.png"))); // NOI18N
        btnInicio.setToolTipText("");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });

        btnPasajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/icono_casa.png"))); // NOI18N
        btnPasajeros.setToolTipText("");
        btnPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPasajerosMouseClicked(evt);
            }
        });

        btngestioncabinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/icono_casa.png"))); // NOI18N
        btngestioncabinas.setToolTipText("");
        btngestioncabinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnabordarpasajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/icono_casa.png"))); // NOI18N
        btnabordarpasajeros.setToolTipText("");
        btnabordarpasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnmostrarcolas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/icono_casa.png"))); // NOI18N
        btnmostrarcolas.setToolTipText("");
        btnmostrarcolas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/boton2.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/grupo4/resources/images/boton2.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout OpcionesLayout = new javax.swing.GroupLayout(Opciones);
        Opciones.setLayout(OpcionesLayout);
        OpcionesLayout.setHorizontalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnInicio)
                .addGap(133, 133, 133)
                .addComponent(btnPasajeros)
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngestioncabinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addComponent(btnabordarpasajeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnmostrarcolas)
                .addGap(133, 133, 133))
        );
        OpcionesLayout.setVerticalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmostrarcolas)
                    .addComponent(btnPasajeros)
                    .addComponent(btnInicio)
                    .addComponent(btngestioncabinas)
                    .addComponent(btnabordarpasajeros))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        Fondo.add(Opciones, java.awt.BorderLayout.SOUTH);

        Inicio.setBackground(new java.awt.Color(0, 0, 0,200));

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        Fondo.add(Inicio, java.awt.BorderLayout.CENTER);

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPasajerosMouseClicked
        ((PanelFondo)Fondo).moverLogoAEsquinaIzquierda();
    }//GEN-LAST:event_btnPasajerosMouseClicked

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        ((PanelFondo)Fondo).moverLogoAlCentro();
    }//GEN-LAST:event_btnInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Opciones;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnPasajeros;
    private javax.swing.JLabel btnabordarpasajeros;
    private javax.swing.JLabel btngestioncabinas;
    private javax.swing.JLabel btnmostrarcolas;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
