/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ed.grupo4.GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author USER
 */
public class PanelAbordarPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form PanelAbordarPasajeros
     */
    private DefaultTableModel modeloDeColaDePasajeros;
    private DefaultTableModel modeloDePasajerosEnCabina;
    
    public PanelAbordarPasajeros() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        modeloDeColaDePasajeros=(DefaultTableModel)colaDePasajeros.getModel();
        ((DefaultTableCellRenderer)colaDePasajeros.getDefaultRenderer(String.class)).setHorizontalAlignment(JLabel.CENTER);
        //JTableHeader headerDeCola=colaDePasajeros.getTableHeader();
        modeloDePasajerosEnCabina=(DefaultTableModel)listaDePasajerosEnCabina.getModel();
        ((DefaultTableCellRenderer)listaDePasajerosEnCabina.getDefaultRenderer(String.class)).setHorizontalAlignment(JLabel.CENTER);
        
        colaDePasajeros.getTableHeader().setDefaultRenderer(new RenderDeCabecera(colaDePasajeros.getTableHeader().getDefaultRenderer()));
        listaDePasajerosEnCabina.getTableHeader().setDefaultRenderer(new RenderDeCabecera(listaDePasajerosEnCabina.getTableHeader().getDefaultRenderer()));
        
        listaDePasajerosEnCabina.getTableHeader().setBackground(Color.WHITE);
        listaDePasajerosEnCabina.getTableHeader().setReorderingAllowed(false);
        listaDePasajerosEnCabina.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        listaDePasajerosEnCabina.getTableHeader().setForeground(new Color(0,51,102,255));
        colaDePasajeros.getTableHeader().setBackground(Color.WHITE);
        colaDePasajeros.getTableHeader().setReorderingAllowed(false);
        colaDePasajeros.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        colaDePasajeros.getTableHeader().setForeground(new Color(0,51,102,255));
     
        
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setOpaque(false);
        jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane2.getViewport().setBackground(Color.WHITE);
        jScrollPane2.setOpaque(false);
    }
    
    public DefaultTableModel getModeloDeColaDePasajeros(){
        return modeloDeColaDePasajeros;
    }
    
    public DefaultTableModel getModeloDePasajerosEnCabina(){
        return modeloDePasajerosEnCabina;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImagen("/ed/grupo4/resources/images/Interfaz04/Panel04.1.png");
        jScrollPane1 = new javax.swing.JScrollPane();
        colaDePasajeros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new PanelImagen("/ed/grupo4/resources/images/Interfaz04/Panel04.1.png");
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDePasajerosEnCabina = new javax.swing.JTable();
        btnAbordar = new PanelImagen("/ed/grupo4/resources/images/Interfaz04/Panel04.2.png");
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new PanelImagen("/ed/grupo4/resources/images/Interfaz04/Panel04.3.png");
        lblTicket = new javax.swing.JLabel();
        cboCabinas = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1280, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(251, 251));

        colaDePasajeros.setBackground(new java.awt.Color(255, 255, 255));
        colaDePasajeros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        colaDePasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ticket"
            }
        ));
        colaDePasajeros.setEnabled(false);
        colaDePasajeros.setGridColor(new java.awt.Color(0, 0, 0));
        colaDePasajeros.setRowHeight(24);
        colaDePasajeros.setRowMargin(0);
        colaDePasajeros.setRowSelectionAllowed(false);
        colaDePasajeros.setShowGrid(false);
        colaDePasajeros.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(colaDePasajeros);
        if (colaDePasajeros.getColumnModel().getColumnCount() > 0) {
            colaDePasajeros.getColumnModel().getColumn(0).setResizable(false);
            colaDePasajeros.getColumnModel().getColumn(0).setPreferredWidth(175);
            colaDePasajeros.getColumnModel().getColumn(1).setResizable(false);
            colaDePasajeros.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Cola de pasajeros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(251, 251));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Pasajeros en Cabina");

        listaDePasajerosEnCabina.setBackground(new java.awt.Color(255, 255, 255));
        listaDePasajerosEnCabina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        listaDePasajerosEnCabina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ticket"
            }
        ));
        listaDePasajerosEnCabina.setEnabled(false);
        listaDePasajerosEnCabina.setGridColor(new java.awt.Color(0, 0, 0));
        listaDePasajerosEnCabina.setRowHeight(24);
        listaDePasajerosEnCabina.setRowMargin(0);
        listaDePasajerosEnCabina.setRowSelectionAllowed(false);
        listaDePasajerosEnCabina.setShowGrid(false);
        listaDePasajerosEnCabina.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(listaDePasajerosEnCabina);
        if (listaDePasajerosEnCabina.getColumnModel().getColumnCount() > 0) {
            listaDePasajerosEnCabina.getColumnModel().getColumn(0).setResizable(false);
            listaDePasajerosEnCabina.getColumnModel().getColumn(0).setPreferredWidth(175);
            listaDePasajerosEnCabina.getColumnModel().getColumn(1).setResizable(false);
            listaDePasajerosEnCabina.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnAbordar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbordar.setMinimumSize(new java.awt.Dimension(118, 100));
        btnAbordar.setPreferredSize(new java.awt.Dimension(118, 99));
        btnAbordar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAbordarMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Abordar");

        javax.swing.GroupLayout btnAbordarLayout = new javax.swing.GroupLayout(btnAbordar);
        btnAbordar.setLayout(btnAbordarLayout);
        btnAbordarLayout.setHorizontalGroup(
            btnAbordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAbordarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btnAbordarLayout.setVerticalGroup(
            btnAbordarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAbordarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(501, 101));

        lblTicket.setFont(new java.awt.Font("Arial Black", 1, 70)); // NOI18N
        lblTicket.setText("AC-001");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblTicket)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblTicket)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        cboCabinas.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        cboCabinas.setFocusable(false);
        cboCabinas.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnAbordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(cboCabinas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cboCabinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAbordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbordarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbordarMousePressed
        
    }//GEN-LAST:event_btnAbordarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbordar;
    private javax.swing.JComboBox<String> cboCabinas;
    private javax.swing.JTable colaDePasajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JTable listaDePasajerosEnCabina;
    // End of variables declaration//GEN-END:variables
}
