/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ed.grupo4.GUI;

import ed.grupo4.main.main;
import ed.grupo4.model.Cabina;
import ed.grupo4.model.Pasajero;
import java.awt.Color;
import ed.grupo4.util.Dijkstra;
import ed.grupo4.util.UtilidadesDeGrafo;
/**
 *
 * @author USER
 */
public class PanelAgregarPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarPasajeros
     */
    public PanelAgregarPasajeros() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
    }
    
    public void desactivarCampos(){
        txtNombre.setEnabled(false);
        txtEdad.setEnabled(false);
        txtPeso.setEnabled(false);
    }
    
    public void activarCampos(){
        txtNombre.setEnabled(true);
        txtEdad.setEnabled(true);
        txtPeso.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImagen("/ed/grupo4/resources/images/Interfaz02/Interfaz02.1.png");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        cboDestino = new javax.swing.JComboBox<>();
        TicketPanel = new PanelImagen("/ed/grupo4/resources/images/Interfaz02/icono_ticket.png");
        jSeparator1 = new javax.swing.JSeparator();
        lblCodigoTicket = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblNombreTicket = new javax.swing.JLabel();
        lblTarifa = new javax.swing.JLabel();
        btnAgregarPasajero = new javax.swing.JButton();
        btnLimpiarDatos = new javax.swing.JButton();
        TicketPanel1 = new PanelImagen("/ed/grupo4/resources/images/Interfaz02/icono_ticket.png");
        jSeparator3 = new javax.swing.JSeparator();
        lblCodigoTicket1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblNombreTicket1 = new javax.swing.JLabel();
        lblRecorridoOptimo = new javax.swing.JLabel();
        jPanel2 = new PanelImagen("/ed/grupo4/resources/images/Interfaz02/Interfaz02.2.png");
        jPanel3 = new PanelImagen("/ed/grupo4/resources/images/Interfaz02/MAPA2.png");
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRecorridoOptimoMapa = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(476, 376));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Ingreso de datos de Pasajero");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Edad:");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Peso:");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Kg");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Destino:");

        txtNombre.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 102));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtEdad.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(0, 51, 102));

        txtPeso.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 51, 102));

        cboDestino.setBackground(new java.awt.Color(255, 255, 255));
        cboDestino.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        cboDestino.setForeground(new java.awt.Color(0, 51, 102));
        cboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "C", "D", "E", "F", "G", "H" }));
        cboDestino.setFocusable(false);

        TicketPanel.setPreferredSize(new java.awt.Dimension(185, 95));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        lblCodigoTicket.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodigoTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigoTicket.setPreferredSize(new java.awt.Dimension(129, 14));

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 2));

        lblNombreTicket.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreTicket.setPreferredSize(new java.awt.Dimension(129, 14));

        lblTarifa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N

        javax.swing.GroupLayout TicketPanelLayout = new javax.swing.GroupLayout(TicketPanel);
        TicketPanel.setLayout(TicketPanelLayout);
        TicketPanelLayout.setHorizontalGroup(
            TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCodigoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TicketPanelLayout.setVerticalGroup(
            TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCodigoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblNombreTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnAgregarPasajero.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarPasajero.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnAgregarPasajero.setForeground(new java.awt.Color(0, 51, 102));
        btnAgregarPasajero.setText("Agregar Pasajero");
        btnAgregarPasajero.setBorderPainted(false);
        btnAgregarPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarPasajero.setFocusPainted(false);
        btnAgregarPasajero.setFocusable(false);
        btnAgregarPasajero.setRequestFocusEnabled(false);
        btnAgregarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPasajeroActionPerformed(evt);
            }
        });

        btnLimpiarDatos.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiarDatos.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnLimpiarDatos.setForeground(new java.awt.Color(0, 51, 102));
        btnLimpiarDatos.setText("Limpiar Datos");
        btnLimpiarDatos.setBorderPainted(false);
        btnLimpiarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarDatos.setFocusPainted(false);
        btnLimpiarDatos.setFocusable(false);
        btnLimpiarDatos.setRequestFocusEnabled(false);
        btnLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosActionPerformed(evt);
            }
        });

        TicketPanel1.setPreferredSize(new java.awt.Dimension(185, 95));

        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 5));

        lblCodigoTicket1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodigoTicket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigoTicket1.setText("Recorrido Óptimo");

        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 2));

        lblNombreTicket1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreTicket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreTicket1.setText("Perú Skyway");

        lblRecorridoOptimo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblRecorridoOptimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TicketPanel1Layout = new javax.swing.GroupLayout(TicketPanel1);
        TicketPanel1.setLayout(TicketPanel1Layout);
        TicketPanel1Layout.setHorizontalGroup(
            TicketPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(TicketPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRecorridoOptimo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TicketPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCodigoTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TicketPanel1Layout.setVerticalGroup(
            TicketPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCodigoTicket1)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblRecorridoOptimo, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblNombreTicket1)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAgregarPasajero)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(TicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TicketPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarPasajero)
                            .addComponent(btnLimpiarDatos)))
                    .addComponent(TicketPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(351, 376));

        jPanel3.setPreferredSize(new java.awt.Dimension(320, 180));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("MAPA DE ESTACIONES");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Recorrido Óptimo:");

        lblRecorridoOptimoMapa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblRecorridoOptimoMapa.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRecorridoOptimoMapa)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecorridoOptimoMapa)
                    .addComponent(jLabel8))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPasajeroActionPerformed
        try{
            if(main.estacion.numerodecolas()==0) throw new Exception("No hay ninguna cola ni cabina disponible");
            String nombre=txtNombre.getText();
            int edad=Integer.parseInt(txtEdad.getText());
            float peso=Float.parseFloat(txtPeso.getText());
            char destino=((String)cboDestino.getSelectedItem()).charAt(0);
            if(nombre.length()!=0){
                int inicio=0;  // 0=Estacion A, con ayuda del formato ASCII podemos identificar las estaciones como numeros y letras,
                int fin=destino-65;  //no lo mas optimo pero funcional para este proyecto
                String recorridoOptimo=Dijkstra.obtenerCaminoMinimo(UtilidadesDeGrafo.numeroDeEstaciones,
                        inicio, fin, UtilidadesDeGrafo.pesos);
                char estacionDestinoActual=recorridoOptimo.charAt(1); //La siguiente estacion de destino estara en la posicion 1
                int indiceDeCola=-1;
                
                for(int i=0;i<main.estacion.numerodecolas();i++){
                    Cabina cabina=main.estacion.getCabina(i);
                    if(cabina.getDestino().contains(""+estacionDestinoActual)){
                        indiceDeCola=i;
                    }
                }
                if(indiceDeCola==-1) throw new Exception("No existe ninguna cabina que se diriga al destino especificado");
                String Ticket;
                if(main.estacion.tamanioColaPasajeros(indiceDeCola)>0){
                    Pasajero pasajero=main.estacion.getPasajero(indiceDeCola, main.estacion.tamanioColaPasajeros(indiceDeCola)-1);
                    int numeroDeTicket=Integer.parseInt(pasajero.getTicket().substring(3, 6))+1;
                    Ticket=recorridoOptimo.substring(0, 2)+"-"+String.format("%03d", numeroDeTicket);
                }else{
                    Ticket=recorridoOptimo.substring(0, 2)+"-001";
                }
                lblCodigoTicket.setText(Ticket);
                lblNombreTicket.setText(nombre);
                lblTarifa.setText("S/."+(edad>=18?"20":"15"));
                lblRecorridoOptimo.setText(recorridoOptimo);
                lblRecorridoOptimoMapa.setText(recorridoOptimo);
                main.estacion.agregarPasajero(indiceDeCola, nombre, edad, peso, Ticket);
            }else{
                throw new Exception("No se ha ingresado el nombre del pasajero");
            }
        }catch(NumberFormatException e){
            System.out.println("La edad o el peso no son validos");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarPasajeroActionPerformed

    private void btnLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosActionPerformed
        txtNombre.setText("");
        txtEdad.setText("");
        txtPeso.setText("");
        lblCodigoTicket.setText("");
        lblNombreTicket.setText("");
        lblTarifa.setText("");
        lblRecorridoOptimo.setText("");
        lblRecorridoOptimoMapa.setText("");
    }//GEN-LAST:event_btnLimpiarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TicketPanel;
    private javax.swing.JPanel TicketPanel1;
    private javax.swing.JButton btnAgregarPasajero;
    private javax.swing.JButton btnLimpiarDatos;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodigoTicket;
    private javax.swing.JLabel lblCodigoTicket1;
    private javax.swing.JLabel lblNombreTicket;
    private javax.swing.JLabel lblNombreTicket1;
    private javax.swing.JLabel lblRecorridoOptimo;
    private javax.swing.JLabel lblRecorridoOptimoMapa;
    private javax.swing.JLabel lblTarifa;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
