/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ed.grupo4.GUI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PanelGestionDeCabinas extends javax.swing.JPanel {
    
    private DefaultTableModel modeloDeTablaDeGestionDeCabina;
    
    public PanelGestionDeCabinas() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        modeloDeTablaDeGestionDeCabina=(DefaultTableModel)tablaDeGestionDeCabinas.getModel();
        ((DefaultTableCellRenderer)tablaDeGestionDeCabinas.getDefaultRenderer(String.class)).setHorizontalAlignment(JLabel.CENTER);
        
        tablaDeGestionDeCabinas.getTableHeader().setDefaultRenderer(new RenderDeCabecera(tablaDeGestionDeCabinas.getTableHeader().getDefaultRenderer()));
        
        tablaDeGestionDeCabinas.getTableHeader().setBackground(Color.WHITE);
        tablaDeGestionDeCabinas.getTableHeader().setReorderingAllowed(false);
        tablaDeGestionDeCabinas.getTableHeader().setFont(new Font("Arial",Font.BOLD,12));
        tablaDeGestionDeCabinas.getTableHeader().setForeground(new Color(0,51,102,255));
        
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setOpaque(false);
        
    }
    
    public DefaultTableModel getModeloDeTabla(){
        return modeloDeTablaDeGestionDeCabina;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImagen("/ed/grupo4/resources/images/Interfaz06/Panel06.1.png");
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeGestionDeCabinas = new javax.swing.JTable();
        lblTituloDeCola = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(501, 376));

        tablaDeGestionDeCabinas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaDeGestionDeCabinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cabina 01", "10", "400", "En estación", "ABCDEFGH"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "# Asientos", "Peso límite", "Estado", "Ruta"
            }
        ));
        tablaDeGestionDeCabinas.setFocusable(false);
        tablaDeGestionDeCabinas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaDeGestionDeCabinas.setRowHeight(32);
        tablaDeGestionDeCabinas.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tablaDeGestionDeCabinas);
        if (tablaDeGestionDeCabinas.getColumnModel().getColumnCount() > 0) {
            tablaDeGestionDeCabinas.getColumnModel().getColumn(0).setPreferredWidth(75);
            tablaDeGestionDeCabinas.getColumnModel().getColumn(1).setPreferredWidth(35);
            tablaDeGestionDeCabinas.getColumnModel().getColumn(2).setPreferredWidth(40);
            tablaDeGestionDeCabinas.getColumnModel().getColumn(3).setPreferredWidth(55);
            tablaDeGestionDeCabinas.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        lblTituloDeCola.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblTituloDeCola.setForeground(new java.awt.Color(0, 51, 102));
        lblTituloDeCola.setText("Gestion de Cabinas");

        btnAñadir.setBackground(new java.awt.Color(204, 204, 204));
        btnAñadir.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(0, 51, 102));
        btnAñadir.setText("Añadir");
        btnAñadir.setBorderPainted(false);
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.setFocusPainted(false);
        btnAñadir.setFocusable(false);
        btnAñadir.setRequestFocusEnabled(false);

        btnModificar.setBackground(new java.awt.Color(204, 204, 204));
        btnModificar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 102));
        btnModificar.setText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.setFocusable(false);
        btnModificar.setRequestFocusEnabled(false);

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 51, 102));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(lblTituloDeCola))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblTituloDeCola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloDeCola;
    private javax.swing.JTable tablaDeGestionDeCabinas;
    // End of variables declaration//GEN-END:variables
}
